api_platform:
    title: 'API MDL'
    description: 'API MDL'
    metadata_backward_compatibility_layer: false
    defaults:
        pagination_enabled: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]